import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { ArrowRight, Shield, Cpu, Database, Activity } from "lucide-react";
export default function Home() {
    return (_jsxs("div", { className: "flex flex-col gap-24 py-12 overflow-hidden", children: [_jsxs("section", { className: "relative flex flex-col items-center text-center gap-8 max-w-4xl mx-auto", children: [_jsx("div", { className: "absolute -top-24 -left-24 w-96 h-96 bg-primary/20 blur-[120px] rounded-full -z-10 animate-pulse" }), _jsx("div", { className: "absolute -bottom-24 -right-24 w-96 h-96 bg-purple-500/20 blur-[120px] rounded-full -z-10" }), _jsxs("div", { className: "inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-bold tracking-wider uppercase animate-fade-in", children: [_jsx(Activity, { size: 14 }), "Powered by 0G High-Performance Stack"] }), _jsxs("h1", { className: "text-5xl md:text-7xl font-outfit font-black tracking-tight leading-[1.1] animate-fade-in", children: ["Autonomous AI for ", _jsx("br", {}), _jsx("span", { className: "text-gradient", children: "Section 8 Investing" })] }), _jsx("p", { className: "text-lg md:text-xl text-muted max-w-2xl animate-fade-in [animation-delay:200ms]", children: "Deploy a persistent agent that continuously scans, analyzes, and executes on-chain real estate deals with verifiable reasoning." }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 mt-4 animate-fade-in [animation-delay:400ms]", children: [_jsxs(Link, { href: "/dashboard", className: "btn-primary flex items-center gap-2 group", children: ["Launch Your Agent", _jsx(ArrowRight, { size: 18, className: "group-hover:translate-x-1 transition-transform" })] }), _jsx(Link, { href: "/market", className: "btn-secondary", children: "Browse Market" })] })] }), _jsx("section", { className: "grid grid-cols-1 md:grid-cols-3 gap-8 px-4", children: [
                    {
                        icon: _jsx(Shield, { className: "text-blue-500", size: 32 }),
                        title: "Verifiable Identity",
                        desc: "Persistent Agent IDs linked to your wallet, ensuring accountability and trust."
                    },
                    {
                        icon: _jsx(Cpu, { className: "text-purple-500", size: 32 }),
                        title: "0G Compute Analysis",
                        desc: "Advanced ROI and cashflow calculations executed via 0G's decentralized compute."
                    },
                    {
                        icon: _jsx(Database, { className: "text-green-500", size: 32 }),
                        title: "Memory Persistence",
                        desc: "All scans and decisions are stored in 0G Storage, creating a long-term data layer."
                    }
                ].map((feature, i) => (_jsxs("div", { className: "glass-card p-8 flex flex-col gap-4 hover:border-primary/30 transition-all group", children: [_jsx("div", { className: "w-12 h-12 rounded-xl bg-white/5 flex items-center justify-center group-hover:scale-110 transition-transform", children: feature.icon }), _jsx("h3", { className: "text-xl font-bold font-outfit", children: feature.title }), _jsx("p", { className: "text-muted leading-relaxed", children: feature.desc })] }, i))) }), _jsxs("section", { className: "glass-card p-12 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 w-1/2 h-full bg-linear-to-l from-primary/5 to-transparent -z-10" }), _jsxs("div", { className: "flex flex-col md:flex-row items-center gap-12", children: [_jsxs("div", { className: "flex-1 flex flex-col gap-6", children: [_jsx("h2", { className: "text-3xl font-outfit font-bold", children: "The Autonomous Loop" }), _jsx("p", { className: "text-muted", children: "Sect8 agents don't just wait for you. They work 24/7 scanning HUD data, calculating Section 8 caps, and identifying the highest-yield properties before they hit the mainstream market." }), _jsx("ul", { className: "space-y-4", children: [
                                            "Data Ingestion from Zillow & HUD",
                                            "Deep Financial Modeling on 0G Compute",
                                            "On-chain Logging of Recommendations",
                                            "Automated Portfolio Rebalancing"
                                        ].map((item, i) => (_jsxs("li", { className: "flex items-center gap-3 text-sm font-medium", children: [_jsx("div", { className: "w-1.5 h-1.5 rounded-full bg-primary" }), item] }, i))) })] }), _jsxs("div", { className: "flex-1 w-full bg-black/40 rounded-2xl border border-white/5 p-6 font-mono text-xs text-blue-400 shadow-2xl", children: [_jsxs("div", { className: "flex gap-2 mb-4", children: [_jsx("div", { className: "w-3 h-3 rounded-full bg-red-500/50" }), _jsx("div", { className: "w-3 h-3 rounded-full bg-yellow-500/50" }), _jsx("div", { className: "w-3 h-3 rounded-full bg-green-500/50" })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("p", { children: [_jsx("span", { className: "text-zinc-500", children: "[13:42:01]" }), " Fetching latest data from HUD API..."] }), _jsxs("p", { children: [_jsx("span", { className: "text-zinc-500", children: "[13:42:05]" }), " Processing 1,240 properties in Detroit area."] }), _jsxs("p", { children: [_jsx("span", { className: "text-zinc-500", children: "[13:42:12]" }), " ", _jsx("span", { className: "text-white", children: "Analysis complete." }), " Found 3 high-yield deals."] }), _jsxs("p", { children: [_jsx("span", { className: "text-zinc-500", children: "[13:42:15]" }), " Calculating Section 8 ROI via 0G Compute..."] }), _jsxs("p", { children: [_jsx("span", { className: "text-zinc-500", children: "[13:42:20]" }), " ", _jsx("span", { className: "text-green-400", children: "Deal Identified:" }), " 123 Maple St. (ROI: 16.4%)"] }), _jsxs("p", { children: [_jsx("span", { className: "text-zinc-500", children: "[13:42:22]" }), " Storing recommendation hash to 0G Storage..."] }), _jsxs("p", { children: [_jsx("span", { className: "text-zinc-500", children: "[13:42:25]" }), " ", _jsx("span", { className: "text-purple-400", children: "On-chain Log:" }), " tx_0x8f32...a12c"] }), _jsx("p", { className: "animate-pulse", children: "_" })] })] })] })] })] }));
}
