"use client";
import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
export default function HeroSection({ recommendations }) {
    const total = (recommendations === null || recommendations === void 0 ? void 0 : recommendations.length) || 0;
    const top3 = recommendations.slice(0, 3);
    const confidence = Math.round((top3.reduce((s, r) => s + (r.confidence || (r.capRate || 0)), 0) / (top3.length || 1)) * 1) || 0;
    return (_jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: "col-span-2 glass-card p-6", children: [_jsxs("h3", { className: "text-xl font-bold", children: ["Your Agent Found ", total, " High-Quality Opportunities"] }), _jsxs("div", { className: "flex items-center gap-6 mt-4", children: [_jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-4xl font-outfit font-black", children: total }), _jsx("div", { className: "text-muted text-sm", children: "Properties scanned" })] }), _jsxs("div", { className: "text-center", children: [_jsxs("div", { className: "text-4xl font-outfit font-black", children: [confidence, "%"] }), _jsx("div", { className: "text-muted text-sm", children: "Confidence Score" })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 mt-6", children: top3.map((r, i) => (_jsxs("div", { className: "p-3 rounded-xl bg-white/5 border border-white/5 flex flex-col gap-3", children: [_jsx("div", { className: "w-full h-28 rounded-md overflow-hidden bg-zinc-800", children: r.image ? (
                                    // eslint-disable-next-line @next/next/no-img-element
                                    _jsx("img", { src: r.image, alt: r.address, className: "w-full h-full object-cover" })) : (_jsx("div", { className: "w-full h-full flex items-center justify-center text-sm text-muted", children: "No image" })) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "font-bold text-sm md:text-base", children: r.address }), _jsxs("div", { className: "text-sm text-muted", children: ["Price: $", r.purchasePrice] }), _jsxs("div", { className: "mt-1 text-sm", children: ["Est Rent: $", r.estRent] })] }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "text-sm", children: ["ROI ", Number((r.capRate || 0)).toFixed(1), "%"] }), _jsx("div", { className: `mt-2 font-bold ${r.isBanger ? 'text-green-400' : 'text-yellow-300'}`, children: r.isBanger ? 'Top Pick 🔥' : 'Recommended' })] })] })] }, r.id || i))) })] }), _jsxs("div", { className: "glass-card p-6", children: [_jsx("h4", { className: "font-bold", children: "Quick Actions" }), _jsxs("div", { className: "mt-4 flex flex-col gap-3", children: [_jsx("button", { className: "btn-primary", children: "View All Recommendations" }), _jsx("button", { className: "btn-secondary", children: "Adjust Strategy" }), _jsx("button", { className: "btn-secondary", children: "Authorize Server" })] })] })] }));
}
